import '@/app/globals.css'
import '@/app/app.css'
export const metadata = {
	title: 'Gro-u App',
	description: 'Generated by create next app',
}
const RootLayout = ({ children }) => {
	return (
		<html lang="es">
			<body>
				{children}
			</body>
		</html>
	)
}

export default RootLayout
